trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: |
    echo hello from macOS
    mkdir /tmp/fortify-sca/
    curl https://blobstorageromell.blob.core.windows.net/container1/fortify-mac.zip --output /tmp/fortify-sca/fortify.zip
    cd /tmp/fortify-sca/
    unzip fortify.zip
    ls -la *
  displayName: 'Installing Fortify'
