trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: |
    echo hello from macOS
    mkdir /opt/fortify-sca/
    curl https://blobstorageromell.blob.core.windows.net/container1/fortify-mac.zip --output /opt/fortify-sca/fortify.zip
    unzip /opt/fortify-sca/fortify.zip/fortify.zip
    ls -la /opt/fortify-sca/
  displayName: 'installing fortify'
